FROM rust:alpine as builder

RUN apk add --no-cache musl-dev

WORKDIR /app

COPY . /app

RUN cargo build --release


FROM alpine:latest as runner

COPY --from=builder /app/target/release/* .

ENTRYPOINT ["./aligner-cli"]