version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    expose:
      - 9093
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    healthcheck:
      test:
        [
          "CMD",
          "kafka-topics.sh",
          "--list",
          "--zookeeper",
          "zookeeper:2181"
        ]
      interval: 30s
      timeout: 10s
      retries: 4

  mariadb:
    image: lscr.io/linuxserver/mariadb:alpine
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=aligner
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=aligner
      - MYSQL_PASSWORD=aligner
      - TZ=Europe/Moscow
    volumes:
      - mariadb_data:/config

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mariadb_data:
    driver: local
