name: aligner
version: "0.1"
author: Lev M. <asertolpas@gmail.com>
about: Utility to align two sequences
args:
      - hello-world:
              about: Prints "Hello, world!"
              short: h
              long: hello-world
      - INPUT:
              about: Sets the input file to use
              required: true
              index: 1
      - deletions:
              about: Sets value for deletions
              short: d
              long: deletions
              takes_value: true
      - matrix:
              about: Sets matrix to be used in aligning
              short: m
              long: matrix
              required: true
              takes_value: true
              value_name: MATRIX
