@startuml

database "Внешние данные" as data
participant "Режим работы утилиты" as calc
participant "Поиск дисперстных\nповторов" as search
participant "Вычисление выравнивания" as align

autonumber
calc -> search: Поиск дисперстных повторов
search -> search: Предобработка последовательности
search -> search: Генерация и трансформация матрицы
search -> align: Расчёт стартовых среднего значения\nи среднеквадратического отклонения
align --> search: Стартовые среднее значение\nи среднеквадратическое отклонение
loop Итерационная процедура
    search -> align: Обход последовательности
    align --> search: Результат обхода последовательности
    search -> search: Пересчёт среднего значения\nи среднеквадратического отклонения
    search -> search: Получение и трансформация частотной матрицы
end
opt Требуется обход "перевёрнутой" последовательности
    search -> align: Обход "перевёрнутой" последовательности
    align --> search: Результат обхода "перевёрнутой" последовательности
end
search --> calc: Найденные дисперстные повторы

@enduml