@startuml

database "Внешние данные" as data
control "Выбор режима" as router
participant "Режим исследования" as exp
participant "Поиск дисперсных\nповторов" as search

autonumber
router -> exp: Переход в режим исследования
data -> exp: Получение последовательности
exp -> search: Поиск дисперсных повторов
search --> exp: Полученение найденных дисперсных повторов
exp --> router: Получение результата поиска дисперсных\nповторов

@enduml