@startuml

database "Внешние данные" as data
control "Выбор режима" as router
participant "Режим csv" as csv
participant "Поиск дисперсных\nповторов" as search

autonumber
router -> csv: Переход в режим csv
data -> csv: Получение последовательности
data -> csv: Получение списка известных дисперсных повторов
csv -> csv: Разметка последовательности
csv -> search: Поиск дисперсных повторов
search --> csv: Получение найденных дисперсных\nповторов
csv --> router: Получение результата поиска дополнительных семейств\nдисперсных повторов

@enduml