@startuml

database "Внешние данные" as data
participant "Режим работы утилиты" as calc
participant "Поиск дисперсных\nповторов" as search
participant "Вычисление выравнивания" as align

autonumber
calc -> search: Поиск дисперсных повторов
search -> search: Предобработка последовательности
search -> search: Генерация и трансформация матрицы
search -> align: Расчёт стартовых среднего значения\nи среднеквадратического отклонения
align --> search: Получение стартовых среднего значения\nи среднеквадратического отклонения
loop Итерационная процедура
    search -> align: Обход последовательности
    align --> search: Получение результата обхода последовательности
    search -> search: Пересчёт среднего значения\nи среднеквадратического отклонения
    search -> search: Получение и трансформация частотной матрицы
end
opt Требуется обход "перевёрнутой" последовательности
    search -> align: Обход "перевёрнутой" последовательности
    align --> search: Получение результата обхода "перевёрнутой" последовательности
end
search --> calc: Получение найденных дисперсных повторов

@enduml