@startuml

database "Внешние данные" as data
control "Выбор режима" as router
participant "Режим тестирования" as test
participant "Выравнивание без\nзаранее заданых матриц" as align
participant "Поиск дисперстных\nповторов" as search

autonumber
router -> test: Переход в режим тестирования
test -> test: Генерация случайной последовательности
test -> align: Запрос на выравнивание\nсгенерированной последовательности
align --> test: Матрица для полученной последовательности
test -> test: Создание 10 потомков последовательности
test -> test: Создание последовательности с 10 потомками внутри
test -> search: Вычисление одного цикла алгоритма\nпоиска дисперстных повторов
search --> test: Найденные дисперстные повторы

test --> router: Результат тестирования алгоритмов

@enduml