@startuml

database "Внешние данные" as data
actor Пользователь as user
control "Выбор режима" as router
participant "Режим тестирования" as test
participant "Режим исследования" as exp
participant "Режим csv" as csv

user -> router: Запрос на поиск дисперсных повторов
router -> test: Переход в режим тестирования
test --> router: Получение результата тестирования алгоритмов
alt Указан параметр input
    router -> exp: Переход в режим исследования
    data -> exp: Получение внешних данных
    exp --> router: Получение результата поиска дисперсных повторов
else Указаны параметр input и параметр csv
    router -> csv: Переход в режим csv
    data -> csv: Получение внешних данных
    csv --> router: Получение результата поиска дополнительных семейств\nдисперсных повторов
end
router --> data: Сохранение результатов работы программы
router --> user: Получеение результата работы программы

@enduml